//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC.Connections.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Category_ID { get; set; }
        public string Category_Desc { get; set; }
        public string Category_Color { get; set; }
        public string Category_Image { get; set; }
    }
}
