//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doorfail.Connections.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharityEvent
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Requirements { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> LocationID { get; set; }
        public string CharityEmail { get; set; }
    }
}
