//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doorfail.Connections.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charity
    {
        public string CharityEmail { get; set; }
        public string Name { get; set; }
        public string EIN { get; set; }
        public Nullable<bool> Deductibility { get; set; }
        public string URL { get; set; }
        public string Cause { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public Nullable<System.Guid> LocationID { get; set; }
    }
}
