
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Connections.PL
{

using System;
    using System.Collections.Generic;
    
public partial class CharityEvent
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CharityEvent()
    {

        this.Event_Requirements = new HashSet<Event_Requirements>();

    }


    public int CharityEvent_ID { get; set; }

    public string CharityEventName { get; set; }

    public string CharityEventLocation { get; set; }

    public Nullable<int> CharityEventCharityID { get; set; }

    public Nullable<int> ContactInfoID { get; set; }

    public Nullable<System.DateTime> CharityEventStartDate { get; set; }

    public Nullable<System.DateTime> CharityEventEndDate { get; set; }

    public Nullable<System.DateTime> CharityEventTime { get; set; }

    public string CharityEvent_Email { get; set; }



    public virtual Charity Charity { get; set; }

    public virtual Contact_Info Contact_Info { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Event_Requirements> Event_Requirements { get; set; }

}

}
