
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Connections.PL
{

using System;
    using System.Collections.Generic;
    
public partial class CharityEvent
{

    public int CharityEvent_ID { get; set; }

    public string CharityEventName { get; set; }

    public string CharityEventLocation { get; set; }

    public Nullable<int> CharityEventCharityID { get; set; }

    public Nullable<int> ContactInfoID { get; set; }

    public Nullable<System.DateTime> CharityEventStartDate { get; set; }

    public Nullable<System.DateTime> CharityEventEndDate { get; set; }

    public Nullable<System.DateTime> CharityEventTime { get; set; }

    public string CharityEvent_Email { get; set; }

}

}
