
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Connections.PL
{

using System;
    using System.Collections.Generic;
    
public partial class Contact_Info
{

    public int Contact_Info_ID { get; set; }

    public string Contact_Info_FName { get; set; }

    public string Contact_Info_LName { get; set; }

    public string Contact_Info_Address { get; set; }

    public string Contact_Info_City { get; set; }

    public string Contact_Info_State { get; set; }

    public string Contact_Info_Zip { get; set; }

    public string Contact_Info_Phone { get; set; }

    public string Contact_Info_Email { get; set; }

}

}
