
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Connections.PL
{

using System;
    using System.Collections.Generic;
    
public partial class Contact_Info
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Contact_Info()
    {

        this.CharityEvents = new HashSet<CharityEvent>();

        this.Members = new HashSet<Member>();

    }


    public int Contact_Info_ID { get; set; }

    public string Contact_Info_FName { get; set; }

    public string Contact_Info_LName { get; set; }

    public string Contact_Info_Address { get; set; }

    public string Contact_Info_City { get; set; }

    public string Contact_Info_State { get; set; }

    public string Contact_Info_Zip { get; set; }

    public string Contact_Info_Phone { get; set; }

    public string Contact_Info_Email { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CharityEvent> CharityEvents { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Member> Members { get; set; }

}

}
