

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Connections.PL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DBconnections : DbContext
{
    public DBconnections()
        : base("name=DBconnections")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Charity> Charities { get; set; }

    public virtual DbSet<CharityEvent> CharityEvents { get; set; }

    public virtual DbSet<Contact_Info> Contact_Info { get; set; }

    public virtual DbSet<Event_Requirements> Event_Requirements { get; set; }

    public virtual DbSet<Helping_Action> Helping_Action { get; set; }

    public virtual DbSet<Log_in> Log_in { get; set; }

    public virtual DbSet<Member_Action> Member_Action { get; set; }

    public virtual DbSet<Member_Categories> Member_Categories { get; set; }

    public virtual DbSet<Member_Charities> Member_Charities { get; set; }

    public virtual DbSet<Member_Type> Member_Type { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<NeedsRequirement> NeedsRequirements { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Preference> Preferences { get; set; }

}

}

