
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Connections.PL
{

using System;
    using System.Collections.Generic;
    
public partial class Event_Requirements
{

    public int Event_Requirement_ID { get; set; }

    public Nullable<int> NeedsRequirementsID { get; set; }

    public Nullable<int> CharityEventID { get; set; }



    public virtual CharityEvent CharityEvent { get; set; }

    public virtual NeedsRequirement NeedsRequirement { get; set; }

}

}
