
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Connections.PL
{

using System;
    using System.Collections.Generic;
    
public partial class Event_Attendance
{

    public int EventAttendance_ID { get; set; }

    public Nullable<int> Event_ID { get; set; }

    public Nullable<int> Member_ID { get; set; }

    public string Status { get; set; }

}

}
