//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC.Connections.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Location_ID { get; set; }
        public string ContactInfoAddress { get; set; }
        public string ContactInfoCity { get; set; }
        public string ContactInfoState { get; set; }
        public string ContactInfoZip { get; set; }
    }
}
