//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC.Connections.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_in
    {
        public string ContactInfoEmail { get; set; }
        public Nullable<int> MemberType { get; set; }
        public Nullable<int> LogInMember_ID { get; set; }
        public string LogInPassword { get; set; }
    }
}
