//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doorfail.Connections.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogIn
    {
        public string MemberEmail { get; set; }
        public Nullable<int> MemberType { get; set; }
        public string Password { get; set; }
        public string Key { get; set; }
    }
}
