//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC.Connections.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Action
    {
        public System.Guid ID { get; set; }
        public string Member_Email { get; set; }
        public Nullable<System.Guid> Action_ID { get; set; }
    
        public virtual Helping_Action Helping_Action { get; set; }
    }
}
