
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CC.Connections.PL
{

using System;
    using System.Collections.Generic;
    
public partial class Member_Categories
{

    public int MemberCat_ID { get; set; }

    public Nullable<int> MemberCat_Categories_ID { get; set; }

    public Nullable<int> MemberCat_Member_ID { get; set; }



    public virtual Category Category { get; set; }

    public virtual Member Member { get; set; }

}

}
