//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC.Connections.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preferred_Charity
    {
        public System.Guid ID { get; set; }
        public string Volunteer_Email { get; set; }
        public string Charity_Email { get; set; }
    }
}
