//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doorfail.Connections.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferredCategory
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public string VolunteerEmail { get; set; }
    }
}
